name: Auto Check-in Bot

on:
  schedule:
    - cron: '0 0 * * 1-5' # 07:00 Thailand = 00:00 UTC, Monday–Friday
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run check-in script
        run: |
          echo "import requests
url = 'https://bpps.ac.th/pmis/attendance_add.php'
data = {
    'key': '1579900157943',
    'submit': 'บันทึกข้อมูล'
}
headers = {
    'User-Agent': 'Mozilla/5.0'
}
response = requests.post(url, data=data, headers=headers)
if 'บันทึก' in response.text:
    print('✅ ลงชื่อเข้างานเรียบร้อยแล้ว')
else:
    print('❌ ไม่สำเร็จ:', response.status_code)
    print(response.text)" > checkin.py
          python3 checkin.py
