name: Auto Check-in Bot

on:
  schedule:
    - cron: '0 0 * * 1-5' # 07:00 Thailand = 00:00 UTC, Monday–Friday
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run check-in script
        run: |
          echo "import requests" > checkin.py
          echo "url = 'https://bpps.ac.th/pmis/attendance_add.php'" >> checkin.py
          echo "data = {" >> checkin.py
          echo "    'key': '1579900157943'," >> checkin.py
          echo "    'submit': 'บันทึกข้อมูล'" >> checkin.py
          echo "}" >> checkin.py
          echo "headers = {" >> checkin.py
          echo "    'User-Agent': 'Mozilla/5.0'" >> checkin.py
          echo "}" >> checkin.py
          echo "response = requests.post(url, data=data, headers=headers)" >> checkin.py
          echo "if 'บันทึก' in response.text:" >> checkin.py
          echo "    print('✅ ลงชื่อเข้างานเรียบร้อยแล้ว')" >> checkin.py
          echo "else:" >> checkin.py
          echo "    print('❌ ไม่สำเร็จ:', response.status_code)" >> checkin.py
          echo "    print(response.text)" >> checkin.py
          python3 checkin.py
